"""Content brief lookup for AI for Small Business cluster (brief id → metadata)."""

BRIEFS = {
    1: {"slug": "how-much-does-ai-cost-for-small-business", "title": "How Much Does AI Cost for a Small Business?", "primary_keyword": "AI cost for small business"},
    2: {"slug": "ai-tools-that-save-small-business-owners-time", "title": "What AI Tools Actually Save Small Business Owners Time?", "primary_keyword": "AI tools that save time small business"},
    3: {"slug": "use-ai-without-hiring-a-developer", "title": "Can I Use AI Without Hiring a Developer?", "primary_keyword": "no-code AI for small business"},
    4: {"slug": "which-ai-tool-should-i-choose-for-my-small-business", "title": "Which AI Tool Should I Choose for My Small Business?", "primary_keyword": "best AI tool for small business"},
    5: {"slug": "automate-customer-follow-ups-with-ai", "title": "How to Automate Customer Follow-ups with AI?", "primary_keyword": "AI customer follow-up automation"},
    6: {"slug": "ai-chatbot-cost-for-small-businesses", "title": "What Does an AI Chatbot Cost for Small Businesses?", "primary_keyword": "AI chatbot cost small business"},
    7: {"slug": "can-ai-help-with-sales-and-customer-service", "title": "Can AI Help Me with Sales and Customer Service?", "primary_keyword": "AI for sales and customer service"},
    8: {"slug": "how-do-i-know-if-ai-is-right-for-my-business", "title": "How Do I Know If AI Is Right for My Business?", "primary_keyword": "is AI right for my business"},
    9: {"slug": "10-20-70-rule-for-ai-implementation", "title": "What Is the 10-20-70 Rule for AI Implementation?", "primary_keyword": "10-20-70 rule AI implementation"},
    10: {"slug": "use-ai-to-analyze-customer-buying-patterns", "title": "How to Use AI to Analyze Customer Buying Patterns?", "primary_keyword": "AI customer buying pattern analysis"},
    11: {"slug": "will-ai-replace-my-employees", "title": "Will AI Replace My Employees?", "primary_keyword": "will AI replace employees small business"},
    12: {"slug": "best-ai-tools-for-scheduling-and-calendar-management", "title": "Best AI Tools for Scheduling and Calendar Management", "primary_keyword": "AI scheduling tools small business"},
    13: {"slug": "get-started-with-ai-if-not-tech-savvy", "title": "How to Get Started with AI If I'm Not Tech-Savvy?", "primary_keyword": "AI for non-technical business owners"},
    14: {"slug": "ai-personalized-offers-for-customers", "title": "Can AI Help Me Create Personalized Offers for Customers?", "primary_keyword": "AI personalized offers small business"},
    15: {"slug": "how-secure-is-ai-for-small-business-data", "title": "How Secure Is AI for My Small Business Data?", "primary_keyword": "AI data security small business"},
    16: {"slug": "ai-tools-small-vs-large-business-differences", "title": "What's the Difference Between AI Tools for Small vs. Large Businesses?", "primary_keyword": "AI tools small business vs enterprise"},
    17: {"slug": "use-ai-to-screen-job-applications", "title": "How to Use AI to Screen Job Applications?", "primary_keyword": "AI resume screening small business"},
    18: {"slug": "ai-for-email-management-and-organization", "title": "Can AI Help with Email Management and Organization?", "primary_keyword": "AI email management small business"},
    19: {"slug": "how-much-time-will-ai-save-my-small-business", "title": "How Much Time Will AI Save My Small Business?", "primary_keyword": "AI time savings small business"},
    20: {"slug": "easiest-ai-tools-for-beginners", "title": "What Are the Easiest AI Tools to Use for Beginners?", "primary_keyword": "easiest AI tools for beginners"},
    21: {"slug": "implement-ai-without-disrupting-business", "title": "How to Implement AI Without Disrupting My Business?", "primary_keyword": "implement AI without disruption"},
    22: {"slug": "which-repetitive-tasks-to-automate-first", "title": "Which Repetitive Tasks Should I Automate with AI First?", "primary_keyword": "which tasks to automate first small business"},
    23: {"slug": "how-ai-improves-customer-support", "title": "How Does AI Improve Customer Support for Small Businesses?", "primary_keyword": "AI customer support small business"},
    24: {"slug": "should-i-hire-someone-to-set-up-ai", "title": "Should I Hire Someone to Set Up AI for My Business?", "primary_keyword": "hire AI consultant small business"},
    25: {"slug": "roi-of-ai-tools-for-small-businesses", "title": "What's the ROI of AI Tools for Small Businesses?", "primary_keyword": "AI ROI small business"},
    26: {"slug": "train-my-team-to-use-ai-tools", "title": "Can I Train My Team to Use AI Tools?", "primary_keyword": "train team AI tools small business"},
    27: {"slug": "ai-developers-vs-no-code-platforms", "title": "How to Choose Between AI Developers and No-Code Platforms?", "primary_keyword": "AI developer vs no-code platform"},
    28: {"slug": "ai-solutions-for-service-based-businesses", "title": "What AI Solutions Work for Service-Based Businesses?", "primary_keyword": "AI for service-based businesses"},
    29: {"slug": "how-long-to-see-results-from-ai-implementation", "title": "How Long Does It Take to See Results from AI Implementation?", "primary_keyword": "AI implementation timeline small business"},
    30: {"slug": "are-free-ai-tools-good-enough", "title": "Are Free AI Tools Good Enough for My Small Business?", "primary_keyword": "free AI tools small business"},
    31: {"slug": "use-ai-for-better-business-analytics", "title": "How to Use AI for Better Business Analytics?", "primary_keyword": "AI business analytics small business"},
    32: {"slug": "questions-to-ask-when-choosing-ai-tool", "title": "What Questions Should I Ask When Choosing an AI Tool?", "primary_keyword": "questions to ask before choosing AI tool"},
    33: {"slug": "can-ai-help-small-businesses-compete-with-larger-companies", "title": "Can AI Help Small Businesses Compete with Larger Companies?", "primary_keyword": "AI small business compete with large companies"},
    34: {"slug": "how-to-measure-success-with-ai-implementation", "title": "How to Measure Success with AI Implementation?", "primary_keyword": "measure AI implementation success"},
    35: {"slug": "common-mistakes-small-businesses-make-with-ai", "title": "What Are the Common Mistakes Small Businesses Make with AI?", "primary_keyword": "small business AI mistakes"},
    36: {"slug": "automate-social-media-posts-with-ai", "title": "How to Automate Social Media Posts with AI?", "primary_keyword": "AI social media automation small business"},
    37: {"slug": "is-ai-implementation-complicated", "title": "Is AI Implementation Complicated for Small Businesses?", "primary_keyword": "is AI implementation complicated"},
    38: {"slug": "what-ai-tools-do-successful-small-businesses-use", "title": "What AI Tools Do Successful Small Businesses Actually Use?", "primary_keyword": "AI tools successful small businesses use"},
    39: {"slug": "get-ai-support-when-something-goes-wrong", "title": "How to Get AI Support When Something Goes Wrong?", "primary_keyword": "AI tool support small business"},
    101: {"slug": "ai-for-inventory-management-and-forecasting", "title": "AI for Inventory Management and Forecasting", "primary_keyword": "AI inventory forecasting small business"},
    102: {"slug": "ai-for-invoice-and-payment-processing", "title": "Using AI for Invoice and Payment Processing", "primary_keyword": "AI invoicing small business"},
    103: {"slug": "ai-powered-business-proposal-generation", "title": "AI-Powered Business Proposal Generation", "primary_keyword": "AI business proposal generator"},
    104: {"slug": "how-ai-improves-employee-productivity", "title": "How AI Improves Employee Productivity", "primary_keyword": "AI employee productivity small business"},
    105: {"slug": "ai-tools-for-market-research-and-competitor-analysis", "title": "AI Tools for Market Research and Competitor Analysis", "primary_keyword": "AI market research small business"},
    106: {"slug": "compliance-and-legal-considerations-for-ai-in-small-business", "title": "Compliance and Legal Considerations for AI in Small Business", "primary_keyword": "AI compliance small business"},
    107: {"slug": "ai-for-personalized-marketing-campaigns", "title": "AI for Personalized Marketing Campaigns", "primary_keyword": "AI personalized marketing small business"},
    108: {"slug": "scaling-ai-solutions-as-your-business-grows", "title": "Scaling AI Solutions as Your Business Grows", "primary_keyword": "scaling AI small business growth"},
    109: {"slug": "integration-of-ai-with-existing-business-software", "title": "Integration of AI with Existing Business Software", "primary_keyword": "AI integration existing software"},
    110: {"slug": "industry-specific-ai-solutions-retail-services-ecommerce", "title": "Industry-Specific AI Solutions (Retail, Services, E-commerce)", "primary_keyword": "industry-specific AI solutions small business"},
}


def slugs_for_briefs(brief_ids):
    return [BRIEFS[b]["slug"] for b in brief_ids if b in BRIEFS]
