"""Content brief lookup for AI for Small Business cluster (brief id → metadata)."""

BRIEFS = {
    1: {"slug": "how-much-does-ai-cost-for-small-business", "title": "How Much Does AI Cost for a Small Business?", "primary_keyword": "AI cost for small business"},
    2: {"slug": "ai-tools-that-save-small-business-owners-time", "title": "What AI Tools Actually Save Small Business Owners Time?", "primary_keyword": "AI tools that save time small business"},
    3: {"slug": "use-ai-without-hiring-a-developer", "title": "Can I Use AI Without Hiring a Developer?", "primary_keyword": "no-code AI for small business"},
    4: {"slug": "which-ai-tool-should-i-choose-for-my-small-business", "title": "Which AI Tool Should I Choose for My Small Business?", "primary_keyword": "best AI tool for small business"},
    5: {"slug": "automate-customer-follow-ups-with-ai", "title": "How to Automate Customer Follow-ups with AI?", "primary_keyword": "AI customer follow-up automation"},
    6: {"slug": "ai-chatbot-cost-for-small-businesses", "title": "What Does an AI Chatbot Cost for Small Businesses?", "primary_keyword": "AI chatbot cost small business"},
    7: {"slug": "can-ai-help-with-sales-and-customer-service", "title": "Can AI Help Me with Sales and Customer Service?", "primary_keyword": "AI for sales and customer service"},
    8: {"slug": "how-do-i-know-if-ai-is-right-for-my-business", "title": "How Do I Know If AI Is Right for My Business?", "primary_keyword": "is AI right for my business"},
    9: {"slug": "10-20-70-rule-for-ai-implementation", "title": "What Is the 10-20-70 Rule for AI Implementation?", "primary_keyword": "10-20-70 rule AI implementation"},
    10: {"slug": "use-ai-to-analyze-customer-buying-patterns", "title": "How to Use AI to Analyze Customer Buying Patterns?", "primary_keyword": "AI customer buying pattern analysis"},
    11: {"slug": "will-ai-replace-my-employees", "title": "Will AI Replace My Employees?", "primary_keyword": "will AI replace employees small business"},
    12: {"slug": "best-ai-tools-for-scheduling-and-calendar-management", "title": "Best AI Tools for Scheduling and Calendar Management", "primary_keyword": "AI scheduling tools small business"},
    13: {"slug": "get-started-with-ai-if-not-tech-savvy", "title": "How to Get Started with AI If I'm Not Tech-Savvy?", "primary_keyword": "AI for non-technical business owners"},
    14: {"slug": "ai-personalized-offers-for-customers", "title": "Can AI Help Me Create Personalized Offers for Customers?", "primary_keyword": "AI personalized offers small business"},
    15: {"slug": "how-secure-is-ai-for-small-business-data", "title": "How Secure Is AI for My Small Business Data?", "primary_keyword": "AI data security small business"},
    16: {"slug": "ai-tools-small-vs-large-business-differences", "title": "What's the Difference Between AI Tools for Small vs. Large Businesses?", "primary_keyword": "AI tools small business vs enterprise"},
    17: {"slug": "use-ai-to-screen-job-applications", "title": "How to Use AI to Screen Job Applications?", "primary_keyword": "AI resume screening small business"},
    18: {"slug": "ai-for-email-management-and-organization", "title": "Can AI Help with Email Management and Organization?", "primary_keyword": "AI email management small business"},
    19: {"slug": "how-much-time-will-ai-save-my-small-business", "title": "How Much Time Will AI Save My Small Business?", "primary_keyword": "AI time savings small business"},
    20: {"slug": "easiest-ai-tools-for-beginners", "title": "What Are the Easiest AI Tools to Use for Beginners?", "primary_keyword": "easiest AI tools for beginners"},
    21: {"slug": "implement-ai-without-disrupting-business", "title": "How to Implement AI Without Disrupting My Business?", "primary_keyword": "implement AI without disruption"},
    22: {"slug": "which-repetitive-tasks-to-automate-first", "title": "Which Repetitive Tasks Should I Automate with AI First?", "primary_keyword": "which tasks to automate first small business"},
    23: {"slug": "how-ai-improves-customer-support", "title": "How Does AI Improve Customer Support for Small Businesses?", "primary_keyword": "AI customer support small business"},
    24: {"slug": "should-i-hire-someone-to-set-up-ai", "title": "Should I Hire Someone to Set Up AI for My Business?", "primary_keyword": "hire AI consultant small business"},
    25: {"slug": "roi-of-ai-tools-for-small-businesses", "title": "What's the ROI of AI Tools for Small Businesses?", "primary_keyword": "AI ROI small business"},
    26: {"slug": "train-my-team-to-use-ai-tools", "title": "Can I Train My Team to Use AI Tools?", "primary_keyword": "train team AI tools small business"},
    27: {"slug": "ai-developers-vs-no-code-platforms", "title": "How to Choose Between AI Developers and No-Code Platforms?", "primary_keyword": "AI developer vs no-code platform"},
    28: {"slug": "ai-solutions-for-service-based-businesses", "title": "What AI Solutions Work for Service-Based Businesses?", "primary_keyword": "AI for service-based businesses"},
    29: {"slug": "how-long-to-see-results-from-ai-implementation", "title": "How Long Does It Take to See Results from AI Implementation?", "primary_keyword": "AI implementation timeline small business"},
    30: {"slug": "are-free-ai-tools-good-enough", "title": "Are Free AI Tools Good Enough for My Small Business?", "primary_keyword": "free AI tools small business"},
    31: {"slug": "use-ai-for-better-business-analytics", "title": "How to Use AI for Better Business Analytics?", "primary_keyword": "AI business analytics small business"},
    32: {"slug": "questions-to-ask-when-choosing-ai-tool", "title": "What Questions Should I Ask When Choosing an AI Tool?", "primary_keyword": "questions to ask before choosing AI tool"},
    33: {"slug": "can-ai-help-small-businesses-compete-with-larger-companies", "title": "Can AI Help Small Businesses Compete with Larger Companies?", "primary_keyword": "AI small business compete with large companies"},
    34: {"slug": "how-to-measure-success-with-ai-implementation", "title": "How to Measure Success with AI Implementation?", "primary_keyword": "measure AI implementation success"},
    35: {"slug": "common-mistakes-small-businesses-make-with-ai", "title": "What Are the Common Mistakes Small Businesses Make with AI?", "primary_keyword": "small business AI mistakes"},
    36: {"slug": "automate-social-media-posts-with-ai", "title": "How to Automate Social Media Posts with AI?", "primary_keyword": "AI social media automation small business"},
    37: {"slug": "is-ai-implementation-complicated", "title": "Is AI Implementation Complicated for Small Businesses?", "primary_keyword": "is AI implementation complicated"},
    38: {"slug": "what-ai-tools-do-successful-small-businesses-use", "title": "What AI Tools Do Successful Small Businesses Actually Use?", "primary_keyword": "AI tools successful small businesses use"},
    39: {"slug": "get-ai-support-when-something-goes-wrong", "title": "How to Get AI Support When Something Goes Wrong?", "primary_keyword": "AI tool support small business"},
    101: {"slug": "ai-for-inventory-management-and-forecasting", "title": "AI for Inventory Management and Forecasting", "primary_keyword": "AI inventory forecasting small business"},
    102: {"slug": "ai-for-invoice-and-payment-processing", "title": "Using AI for Invoice and Payment Processing", "primary_keyword": "AI invoicing small business"},
    103: {"slug": "ai-powered-business-proposal-generation", "title": "AI-Powered Business Proposal Generation", "primary_keyword": "AI business proposal generator"},
    104: {"slug": "how-ai-improves-employee-productivity", "title": "How AI Improves Employee Productivity", "primary_keyword": "AI employee productivity small business"},
    105: {"slug": "ai-tools-for-market-research-and-competitor-analysis", "title": "AI Tools for Market Research and Competitor Analysis", "primary_keyword": "AI market research small business"},
    106: {"slug": "compliance-and-legal-considerations-for-ai-in-small-business", "title": "Compliance and Legal Considerations for AI in Small Business", "primary_keyword": "AI compliance small business"},
    107: {"slug": "ai-for-personalized-marketing-campaigns", "title": "AI for Personalized Marketing Campaigns", "primary_keyword": "AI personalized marketing small business"},
    108: {"slug": "scaling-ai-solutions-as-your-business-grows", "title": "Scaling AI Solutions as Your Business Grows", "primary_keyword": "scaling AI small business growth"},
    109: {"slug": "integration-of-ai-with-existing-business-software", "title": "Integration of AI with Existing Business Software", "primary_keyword": "AI integration existing software"},
    110: {"slug": "industry-specific-ai-solutions-retail-services-ecommerce", "title": "Industry-Specific AI Solutions (Retail, Services, E-commerce)", "primary_keyword": "industry-specific AI solutions small business"},
    201: {"slug": "chatgpt-for-small-business-owners", "title": 'ChatGPT for Small Business Owners: Practical Uses That Save Time', "primary_keyword": 'ChatGPT for small business owners'},
    202: {"slug": "ai-for-google-business-reviews", "title": 'How to Use AI for Google Business Reviews Without Sounding Fake', "primary_keyword": 'AI Google Business reviews small business'},
    203: {"slug": "ai-phone-answering-for-small-business", "title": 'AI Phone Answering for Small Businesses: When It Helps and When It Hurts', "primary_keyword": 'AI phone answering small business'},
    204: {"slug": "ai-for-appointment-reminders-and-no-shows", "title": 'Using AI for Appointment Reminders and Reducing No-Shows', "primary_keyword": 'AI appointment reminders reduce no-shows'},
    205: {"slug": "ai-for-local-seo-small-business", "title": 'AI for Local SEO: Practical Ways Small Businesses Can Rank Nearby', "primary_keyword": 'AI for local SEO small business'},
    206: {"slug": "ai-meeting-notes-for-small-business", "title": 'AI Meeting Notes for Small Business Teams That Actually Follow Through', "primary_keyword": 'AI meeting notes small business'},
    207: {"slug": "ai-for-writing-sops-and-training-guides", "title": 'How to Use AI to Write SOPs and Training Guides Faster', "primary_keyword": 'AI write SOPs small business'},
    208: {"slug": "ai-vs-virtual-assistant-for-small-business", "title": 'AI vs a Virtual Assistant: What Should a Small Business Use First?', "primary_keyword": 'AI vs virtual assistant small business'},
    209: {"slug": "ai-for-lead-qualification", "title": 'AI for Lead Qualification: Score Inquiries Without Losing Good Customers', "primary_keyword": 'AI lead qualification small business'},
    210: {"slug": "ai-for-quote-and-estimate-generation", "title": 'AI for Quotes and Estimates: Faster Drafts with Human Pricing Control', "primary_keyword": 'AI quotes and estimates small business'},
    211: {"slug": "ai-for-home-service-businesses", "title": 'AI for Home Service Businesses: Scheduling, Follow-Up, and Field Notes', "primary_keyword": 'AI for home service businesses'},
    212: {"slug": "ai-for-restaurants-and-hospitality", "title": 'AI for Restaurants and Hospitality: Reservations, Reviews, and Staff Support', "primary_keyword": 'AI for restaurants and hospitality'},
    213: {"slug": "ai-for-contractors-and-trades", "title": 'AI for Contractors and Trades: Estimates, Change Orders, and Client Updates', "primary_keyword": 'AI for contractors and trades'},
    214: {"slug": "ai-for-professional-services-firms", "title": 'AI for Professional Services Firms: Research, Drafting, and Client Prep', "primary_keyword": 'AI for professional services firms'},
    215: {"slug": "ai-for-cash-flow-forecasting", "title": 'AI for Cash Flow Forecasting in Small Businesses', "primary_keyword": 'AI cash flow forecasting small business'},
    216: {"slug": "ai-for-expense-categorization", "title": 'Using AI for Expense Categorization Without Losing Financial Control', "primary_keyword": 'AI expense categorization small business'},
    217: {"slug": "ai-for-vendor-and-supplier-management", "title": 'AI for Vendor and Supplier Management in Growing Small Businesses', "primary_keyword": 'AI vendor management small business'},
    218: {"slug": "should-i-use-chatgpt-or-specialized-ai-tools", "title": 'Should I Use ChatGPT or Specialized AI Tools for My Business?', "primary_keyword": 'ChatGPT vs specialized AI tools'},
    219: {"slug": "ai-for-customer-onboarding", "title": 'AI for Customer Onboarding: Clearer Kickoffs Without Extra Admin', "primary_keyword": 'AI customer onboarding small business'},
    220: {"slug": "ai-for-knowledge-base-and-faqs", "title": 'Build an AI-Ready Knowledge Base and FAQ for Your Small Business', "primary_keyword": 'AI knowledge base FAQ small business'},
    221: {"slug": "how-to-prompt-ai-for-business-tasks", "title": 'How to Prompt AI for Business Tasks (Without Getting Generic Output)', "primary_keyword": 'how to prompt AI for business tasks'},
    222: {"slug": "ai-for-reputation-management", "title": 'AI for Reputation Management: Monitor, Respond, and Improve', "primary_keyword": 'AI reputation management small business'},
    223: {"slug": "ai-content-that-still-sounds-like-your-brand", "title": 'How to Create AI Content That Still Sounds Like Your Brand', "primary_keyword": 'AI content that matches brand voice'},
    224: {"slug": "ai-for-hiring-job-descriptions", "title": 'Using AI to Write Better Job Descriptions for Small Business Hiring', "primary_keyword": 'AI job descriptions small business'},
    225: {"slug": "ai-for-employee-onboarding", "title": 'AI for Employee Onboarding: Faster Ramp Without Cutting Corners', "primary_keyword": 'AI employee onboarding small business'},
    226: {"slug": "when-not-to-use-ai-in-your-business", "title": 'When Not to Use AI in Your Business', "primary_keyword": 'when not to use AI small business'},
    227: {"slug": "ai-for-multi-location-small-businesses", "title": 'AI for Multi-Location Small Businesses: Consistency Without Central Chaos', "primary_keyword": 'AI multi-location small business'},
    228: {"slug": "ai-for-b2b-sales-follow-up", "title": 'AI for B2B Sales Follow-Up That Stays Personal', "primary_keyword": 'AI B2B sales follow-up'},
    229: {"slug": "measuring-ai-adoption-across-your-team", "title": 'How to Measure AI Adoption Across Your Small Business Team', "primary_keyword": 'measure AI adoption small business team'},
    230: {"slug": "ai-for-document-organization-and-search", "title": 'AI for Document Organization and Search in Small Businesses', "primary_keyword": 'AI document organization search small business'},
    231: {"slug": "ai-for-seasonal-demand-planning", "title": 'AI for Seasonal Demand Planning in Small Businesses', "primary_keyword": 'AI seasonal demand planning small business'},
    232: {"slug": "ai-tools-for-solo-entrepreneurs", "title": 'Best-First AI Tools for Solo Entrepreneurs', "primary_keyword": 'AI tools for solo entrepreneurs'},
    233: {"slug": "building-an-ai-policy-for-employees", "title": 'How to Build a Simple AI Policy for Employees', "primary_keyword": 'AI policy for employees small business'},
    234: {"slug": "ai-for-customer-winback-campaigns", "title": 'AI for Customer Win-Back Campaigns That Feel Personal', "primary_keyword": 'AI customer win-back campaigns'},
    235: {"slug": "ai-for-year-end-business-review", "title": 'Using AI for a Year-End Business Review That Drives Next Year’s Plan', "primary_keyword": 'AI year-end business review'},
    236: {"slug": "ai-implementation-roadmap-90-days", "title": 'A 90-Day AI Implementation Roadmap for Small Businesses', "primary_keyword": '90 day AI implementation roadmap small business'},
    301: {"slug": "ai-implementation-tool-stack-for-small-business", "title": 'The AI Implementation Tool Stack We Use with Small Businesses', "primary_keyword": 'AI implementation tool stack small business'},
    302: {"slug": "notion-ai-for-small-business-operations", "title": 'Notion AI for Small Business Operations: SOPs, Projects, and a Living Wiki', "primary_keyword": 'Notion AI for small business operations'},
    303: {"slug": "wispr-flow-for-business-dictation-and-discovery", "title": 'Wispr Flow for Business: Faster Discovery Notes and Cleaner Drafts', "primary_keyword": 'Wispr Flow for business dictation'},
    304: {"slug": "apollo-io-for-small-business-lead-research", "title": 'Apollo.io for Small Business Lead Research and Outreach Prep', "primary_keyword": 'Apollo.io for small business lead research'},
    305: {"slug": "perplexity-ai-for-business-research", "title": 'Perplexity AI for Business Research: Faster Answers with Sources', "primary_keyword": 'Perplexity AI for business research'},
    306: {"slug": "claude-vs-chatgpt-for-small-business-work", "title": 'Claude vs ChatGPT for Small Business Work: What We Use When', "primary_keyword": 'Claude vs ChatGPT for small business'},
    307: {"slug": "zapier-make-n8n-for-small-business-automation", "title": 'Zapier vs Make vs n8n: Choosing Automation for Small Business AI', "primary_keyword": 'Zapier vs Make vs n8n small business'},
    308: {"slug": "using-futurepedia-to-discover-ai-tools", "title": 'Using Futurepedia to Discover AI Tools Without Tool Chaos', "primary_keyword": 'using Futurepedia to discover AI tools'},
    309: {"slug": "calendly-and-scheduling-in-ai-implementations", "title": 'Calendly and Smart Scheduling in AI Implementations', "primary_keyword": 'Calendly AI scheduling small business'},
    310: {"slug": "crm-ai-hubspot-and-lightweight-pipelines", "title": 'CRM AI for Small Business: HubSpot and Lightweight Pipelines', "primary_keyword": 'CRM AI HubSpot small business'},
    311: {"slug": "loom-and-async-video-for-ai-training", "title": 'Loom and Async Video for AI Training Inside Small Businesses', "primary_keyword": 'Loom async video AI training small business'},
    312: {"slug": "google-workspace-and-microsoft-365-ai-copilots", "title": 'Google Workspace and Microsoft 365 Copilots in Small Business AI Rollouts', "primary_keyword": 'Google Workspace Microsoft 365 Copilot small business'},
    313: {"slug": "stripe-and-payments-in-ai-assisted-workflows", "title": 'Stripe and Payments in AI-Assisted Business Workflows', "primary_keyword": 'Stripe AI assisted payment workflows'},
    314: {"slug": "fireflies-and-meeting-intelligence-tools", "title": 'Fireflies and Meeting Intelligence Tools for Small Business Teams', "primary_keyword": 'Fireflies meeting intelligence small business'},
    315: {"slug": "cursor-and-custom-ai-builds-when-no-code-is-not-enough", "title": 'Cursor and Custom AI Builds: When No-Code Is Not Enough', "primary_keyword": 'Cursor AI custom builds small business'},
    316: {"slug": "slack-and-team-ai-assistants", "title": 'Slack and Team AI Assistants Without Notification Chaos', "primary_keyword": 'Slack AI assistants small business'},
    317: {"slug": "airtable-and-structured-ops-data", "title": 'Airtable for Structured Ops Data in AI Implementations', "primary_keyword": 'Airtable AI operations small business'},
    318: {"slug": "figma-and-canva-ai-for-client-facing-assets", "title": 'Figma and Canva AI for Client-Facing Assets in Small Businesses', "primary_keyword": 'Canva AI Figma small business assets'},
    319: {"slug": "security-checklist-for-your-ai-tool-stack", "title": 'A Security Checklist for Your Small Business AI Tool Stack', "primary_keyword": 'AI tool stack security checklist small business'},
    320: {"slug": "measuring-roi-of-your-ai-tool-stack", "title": 'How to Measure ROI of Your AI Tool Stack', "primary_keyword": 'measure ROI AI tool stack small business'},
    321: {"slug": "starter-ai-stack-for-service-businesses", "title": 'A Starter AI Stack for Service Businesses (Home, Pro, and Local Services)', "primary_keyword": 'starter AI stack service businesses'},
    322: {"slug": "starter-ai-stack-for-b2b-and-professional-firms", "title": 'A Starter AI Stack for B2B and Professional Services Firms', "primary_keyword": 'starter AI stack B2B professional services'},
    323: {"slug": "how-peacemakers-runs-an-ai-implementation-week-by-week", "title": 'How Peacemakers Runs an AI Implementation Week by Week (and Which Tools Show Up)', "primary_keyword": 'Peacemakers AI implementation week by week'},
    324: {"slug": "avoiding-ai-tool-sprawl-after-implementation", "title": 'Avoiding AI Tool Sprawl After Implementation', "primary_keyword": 'avoid AI tool sprawl small business'},
}


def slugs_for_briefs(brief_ids):
    return [BRIEFS[b]["slug"] for b in brief_ids if b in BRIEFS]
