/**
 * Default sales pipeline stages and “what happens next” guidance.
 * Seeded into PipelineStage — configurable via DB, not hard-coded in UI.
 */

export type StageSeed = {
  name: string;
  slug: string;
  objective: string;
  requiredInformation: string;
  requiredOwnerAction: string;
  clientFacingArtifact: string | null;
  suggestedMessage: string;
  relevantSopSlug: string | null;
  exitCriteria: string;
  nextStageSlug: string | null;
  isTerminal: boolean;
  checklist: string[];
};

export const DEFAULT_PIPELINE_SLUG = "owner-ops-default";

export const DEFAULT_STAGES: StageSeed[] = [
  {
    name: "New Lead",
    slug: "new-lead",
    objective: "Capture and qualify a new inbound or outbound lead.",
    requiredInformation: "Name, email, company (if known), source.",
    requiredOwnerAction: "Review lead details and decide on intro outreach.",
    clientFacingArtifact: null,
    suggestedMessage:
      "Thanks for reaching out — I’d like to schedule a short introductory call.",
    relevantSopSlug: "sop-new-lead",
    exitCriteria: "Intro call requested or lead disqualified.",
    nextStageSlug: "intro-call-requested",
    isTerminal: false,
    checklist: ["Confirm contact details", "Note lead source"],
  },
  {
    name: "Intro Call Requested",
    slug: "intro-call-requested",
    objective: "Get an introductory discovery call on the calendar.",
    requiredInformation: "Preferred times or Calendly link sent.",
    requiredOwnerAction: "Send scheduling link and follow up if no response.",
    clientFacingArtifact: "Calendly intro link",
    suggestedMessage:
      "Here is my calendar link for a 30-minute introductory call.",
    relevantSopSlug: "sop-intro-scheduling",
    exitCriteria: "Call is scheduled.",
    nextStageSlug: "intro-call-scheduled",
    isTerminal: false,
    checklist: ["Send calendar link", "Set follow-up reminder"],
  },
  {
    name: "Intro Call Scheduled",
    slug: "intro-call-scheduled",
    objective: "Prepare for and hold the introductory call.",
    requiredInformation: "Meeting time, prep notes, company context.",
    requiredOwnerAction: "Prepare talking points; confirm attendance.",
    clientFacingArtifact: null,
    suggestedMessage: "Looking forward to our call — here is a short agenda.",
    relevantSopSlug: "sop-intro-call",
    exitCriteria: "Call completed or rescheduled/cancelled.",
    nextStageSlug: "intro-call-completed",
    isTerminal: false,
    checklist: ["Add meeting record", "Prepare discovery questions"],
  },
  {
    name: "Intro Call Completed",
    slug: "intro-call-completed",
    objective: "Record outcomes and decide qualification.",
    requiredInformation: "Call notes, fit assessment, interest level.",
    requiredOwnerAction: "Mark qualified, nurture, or lost.",
    clientFacingArtifact: null,
    suggestedMessage: "Thank you for the conversation — next steps below.",
    relevantSopSlug: "sop-intro-follow-up",
    exitCriteria: "Qualification decision recorded.",
    nextStageSlug: "qualified",
    isTerminal: false,
    checklist: ["Log call notes", "Decide qualify / nurture / lost"],
  },
  {
    name: "Qualified",
    slug: "qualified",
    objective: "Confirm fit and prepare Blueprint form invitation.",
    requiredInformation: "Confirmed interest and decision-makers.",
    requiredOwnerAction: "Create contact/company/opportunity if missing.",
    clientFacingArtifact: null,
    suggestedMessage:
      "Based on our call, the Business Blueprint preparation form is the next step.",
    relevantSopSlug: "sop-qualify",
    exitCriteria: "Ready to send Blueprint form.",
    nextStageSlug: "blueprint-form-not-sent",
    isTerminal: false,
    checklist: ["Confirm stakeholders", "Confirm company record"],
  },
  {
    name: "Blueprint Form Not Sent",
    slug: "blueprint-form-not-sent",
    objective: "Create and send the Business Blueprint Preparation form.",
    requiredInformation: "Contact email, company association.",
    requiredOwnerAction: "Create invitation and send secure link.",
    clientFacingArtifact: "Business Blueprint Preparation form",
    suggestedMessage:
      "Please complete the Business Blueprint Preparation form before our Blueprint call. You can save and return later.",
    relevantSopSlug: "sop-blueprint-invite",
    exitCriteria: "Invitation created and sent.",
    nextStageSlug: "blueprint-form-sent",
    isTerminal: false,
    checklist: ["Create form invitation", "Send or copy link"],
  },
  {
    name: "Blueprint Form Sent",
    slug: "blueprint-form-sent",
    objective: "Ensure the client received and can open the form.",
    requiredInformation: "Invitation status, expiry date.",
    requiredOwnerAction: "Monitor open status; resend if needed.",
    clientFacingArtifact: "Secure form link",
    suggestedMessage:
      "Friendly reminder: the Blueprint preparation form is ready when you are.",
    relevantSopSlug: "sop-blueprint-follow-up",
    exitCriteria: "Form opened or client confirmed receipt.",
    nextStageSlug: "blueprint-form-started",
    isTerminal: false,
    checklist: ["Confirm delivery", "Schedule follow-up if unopened"],
  },
  {
    name: "Blueprint Form Started",
    slug: "blueprint-form-started",
    objective: "Support the client while they complete the form.",
    requiredInformation: "Completion percentage, last saved time.",
    requiredOwnerAction: "Offer help; track progress.",
    clientFacingArtifact: "In-progress form",
    suggestedMessage:
      "I see you’ve started the form — happy to jump on a quick call if anything is unclear.",
    relevantSopSlug: "sop-blueprint-support",
    exitCriteria: "Submission received or waiting for more input.",
    nextStageSlug: "waiting-for-client",
    isTerminal: false,
    checklist: ["Review completion %", "Offer support if stalled"],
  },
  {
    name: "Waiting for Client",
    slug: "waiting-for-client",
    objective: "Wait for remaining form input without losing momentum.",
    requiredInformation: "Last activity, follow-up cadence.",
    requiredOwnerAction: "Follow up on incomplete form by due date.",
    clientFacingArtifact: "Form resume link",
    suggestedMessage:
      "Just checking in on the Blueprint preparation form — your progress is saved.",
    relevantSopSlug: "sop-waiting-client",
    exitCriteria: "Form submitted or opportunity re-staged.",
    nextStageSlug: "blueprint-form-submitted",
    isTerminal: false,
    checklist: ["Send reminder", "Update next-action due date"],
  },
  {
    name: "Blueprint Form Submitted",
    slug: "blueprint-form-submitted",
    objective: "Acknowledge submission and queue owner review.",
    requiredInformation: "Submitted response version, timestamp.",
    requiredOwnerAction: "Confirm receipt; start review task.",
    clientFacingArtifact: "Submission confirmation",
    suggestedMessage:
      "Thank you — we received your Business Blueprint preparation answers and will review them before our call.",
    relevantSopSlug: "sop-blueprint-submitted",
    exitCriteria: "Review task created and client notified.",
    nextStageSlug: "blueprint-review-required",
    isTerminal: false,
    checklist: ["Send confirmation", "Create review task"],
  },
  {
    name: "Blueprint Review Required",
    slug: "blueprint-review-required",
    objective: "Review answers and prepare for the Blueprint call.",
    requiredInformation: "Full form responses, process maps, files.",
    requiredOwnerAction: "Mark reviewed; schedule Blueprint call.",
    clientFacingArtifact: null,
    suggestedMessage:
      "I’ve reviewed your submission — let’s schedule the Business Blueprint discussion.",
    relevantSopSlug: "sop-blueprint-review",
    exitCriteria: "Marked reviewed and call scheduled or requested.",
    nextStageSlug: "blueprint-call-scheduled",
    isTerminal: false,
    checklist: ["Review submission", "Add internal notes", "Mark reviewed"],
  },
  {
    name: "Blueprint Call Scheduled",
    slug: "blueprint-call-scheduled",
    objective: "Hold the Business Blueprint discussion.",
    requiredInformation: "Meeting time, review notes.",
    requiredOwnerAction: "Prepare recommendations outline.",
    clientFacingArtifact: null,
    suggestedMessage: "Confirming our Blueprint call — agenda attached.",
    relevantSopSlug: "sop-blueprint-call",
    exitCriteria: "Call completed.",
    nextStageSlug: "blueprint-call-completed",
    isTerminal: false,
    checklist: ["Prepare agenda", "Confirm attendance"],
  },
  {
    name: "Blueprint Call Completed",
    slug: "blueprint-call-completed",
    objective: "Capture decisions and move to recommendations.",
    requiredInformation: "Call outcomes, priority processes.",
    requiredOwnerAction: "Draft recommendation priorities.",
    clientFacingArtifact: null,
    suggestedMessage: "Thanks for the Blueprint discussion — recommendations coming next.",
    relevantSopSlug: "sop-blueprint-call-follow-up",
    exitCriteria: "Recommendation work started.",
    nextStageSlug: "recommendation-in-preparation",
    isTerminal: false,
    checklist: ["Log outcomes", "List recommended priorities"],
  },
  {
    name: "Recommendation in Preparation",
    slug: "recommendation-in-preparation",
    objective: "Prepare proposal-ready recommendations.",
    requiredInformation: "Scope outline, priority order, rough value.",
    requiredOwnerAction: "Draft proposal materials.",
    clientFacingArtifact: null,
    suggestedMessage: "I’m preparing a clear recommendation and proposal for your review.",
    relevantSopSlug: "sop-recommendation",
    exitCriteria: "Proposal ready to send.",
    nextStageSlug: "proposal-sent",
    isTerminal: false,
    checklist: ["Draft scope", "Estimate effort/value"],
  },
  {
    name: "Proposal Sent",
    slug: "proposal-sent",
    objective: "Get proposal decision.",
    requiredInformation: "Proposal document, amount, send date.",
    requiredOwnerAction: "Follow up on proposal.",
    clientFacingArtifact: "Proposal",
    suggestedMessage: "Sharing the proposed plan and investment for your review.",
    relevantSopSlug: "sop-proposal",
    exitCriteria: "Accepted, declined, or revised.",
    nextStageSlug: "agreement-sent",
    isTerminal: false,
    checklist: ["Send proposal", "Schedule follow-up"],
  },
  {
    name: "Agreement Sent",
    slug: "agreement-sent",
    objective: "Obtain signed agreement.",
    requiredInformation: "Agreement document, signature status.",
    requiredOwnerAction: "Track signature; answer questions.",
    clientFacingArtifact: "Agreement",
    suggestedMessage: "Agreement is ready for signature when you are.",
    relevantSopSlug: "sop-agreement",
    exitCriteria: "Agreement signed.",
    nextStageSlug: "awaiting-payment",
    isTerminal: false,
    checklist: ["Send agreement", "Confirm signature"],
  },
  {
    name: "Awaiting Payment",
    slug: "awaiting-payment",
    objective: "Collect deposit or initial payment.",
    requiredInformation: "Invoice status, due date.",
    requiredOwnerAction: "Confirm payment received.",
    clientFacingArtifact: "Invoice / payment request",
    suggestedMessage: "Invoice is ready — thank you for getting this started.",
    relevantSopSlug: "sop-payment",
    exitCriteria: "Payment received.",
    nextStageSlug: "won-client",
    isTerminal: false,
    checklist: ["Send invoice", "Confirm payment"],
  },
  {
    name: "Won — Client",
    slug: "won-client",
    objective: "Convert to client and open project work.",
    requiredInformation: "Signed agreement, paid invoice, kickoff plan.",
    requiredOwnerAction: "Create project and onboarding tasks.",
    clientFacingArtifact: "Kickoff materials",
    suggestedMessage: "Welcome — here is what happens next for onboarding.",
    relevantSopSlug: "sop-client-won",
    exitCriteria: "Project opened (Phase 2).",
    nextStageSlug: null,
    isTerminal: true,
    checklist: ["Mark opportunity won", "Plan kickoff"],
  },
  {
    name: "Lost",
    slug: "lost",
    objective: "Close out respectfully with a reason.",
    requiredInformation: "Loss reason, last touch date.",
    requiredOwnerAction: "Record reason; optional nurture later.",
    clientFacingArtifact: null,
    suggestedMessage: "Thank you for exploring this — door remains open.",
    relevantSopSlug: "sop-lost",
    exitCriteria: "Closed with reason.",
    nextStageSlug: null,
    isTerminal: true,
    checklist: ["Record loss reason"],
  },
  {
    name: "Nurture",
    slug: "nurture",
    objective: "Stay in touch until timing improves.",
    requiredInformation: "Nurture cadence, next check-in date.",
    requiredOwnerAction: "Schedule next touchpoint.",
    clientFacingArtifact: null,
    suggestedMessage: "I’ll check back at a better time — here’s a helpful resource.",
    relevantSopSlug: "sop-nurture",
    exitCriteria: "Re-engaged or moved to lost.",
    nextStageSlug: "new-lead",
    isTerminal: false,
    checklist: ["Set nurture next action"],
  },
];

export const BLUEPRINT_FORM_TEMPLATE_SLUG = "business-blueprint-preparation";
